name: Greet

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"


jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Greet
        uses: ./.github/actions/greeting_action
        with:
          who-to-greet: Jesper